services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    container_name: arma3-updater
    env_file:
      - ./arma3_hc_config.env
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3
      - arma3_mods:/arma3/steamapps/workshop/content/107410
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /arma3/start_updater.sh"
    restart: "no"

  arma3-client-0:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: arma3-client-0
    env_file:
      - ./arma3_hc_config.env
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3:ro
      - arma3_mods:/arma3/steamapps/workshop/content/107410
      - logs:/logs
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /scripts/start_client.sh"
    restart: always

  arma3-client-1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: arma3-client-1
    env_file:
      - ./arma3_hc_config.env
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3:ro
      - arma3_mods:/arma3/steamapps/workshop/content/107410
      - logs:/logs
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /scripts/start_client.sh"
    restart: always

volumes:
  arma3_data:
  arma3_mods:
  logs:
