services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    container_name: arma3-updater
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /arma3/start_updater.sh"
    restart: "no"

  arma3-client-0:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: arma3-client-0
    depends_on:
      - updater
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3:ro
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /arma3/start_client.sh"
    restart: always

  arma3-client-1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: arma3-client-1
    depends_on:
      - updater
    volumes:
      - ./arma3_hc_config.env:/arma3/arma3_hc_config.env
      - arma3_data:/arma3:ro
    command: /bin/bash -c "source /arma3/arma3_hc_config.env && /arma3/start_client.sh"
    restart: always

volumes:
  arma3_data:
